<a href="https://colab.research.google.com/github/rishabh1911007/ML-Study-Jam/blob/main/ML_Study_Jam_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd     # used to import, read, manage, work , manipulate, analyze the dataset

In [6]:
import numpy as np        # it is 50 times faster than normal python list and used to 

In [7]:
import matplotlib.pyplot as plt       # used to draw different different graphs, visualize the data and output

In [9]:
from sklearn.model_selection import train_test_split      # sklearn is a very big library in which a function train_test_split is imported to train and test the model

In [12]:
from sklearn.preprocessing import LabelEncoder        # used to convert the labled column which is in string form into the numerical fomrat so that we can train the model 

In [13]:
from sklearn.metrics import accuracy_score        # used to evaluate the accuracy of the model

In [14]:
from sklearn.svm import SVC     # svm is the Support Vector Machines and SVC Support Vector Classifiers  

In [15]:
data= pd.read_csv('/content/Iris.csv')      # u can use the path or the name of the file also

In [16]:
data


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [17]:
print(data)       # u can use print(data) or only data, both will print the data but by the data only code the representation of the data is good

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [18]:
data.shape

(150, 6)

In [19]:
encode=LabelEncoder()         # temp name for LabelEncoder
data.Species= encode.fit_transform(data.Species)        # to convert the string data into numerical data and in bracket and after data. we have to write that particular columns heading name

In [20]:
data        # print the data 


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [23]:
X=data[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm","PetalWidthCm"]]         # assigning the data to the var X 

In [24]:
X


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [25]:
Y=data["Species"]         # assigning the data to var Y

In [26]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [30]:
X=np.array(X)       # converting the list into numpy array

In [31]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [28]:
Y=np.array(Y)

In [29]:
Y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size =0.2)       # here testing data size is 20%

In [33]:
X_train

array([[6.2, 2.2, 4.5, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3. , 5.2, 2. ],
       [7.1, 3. , 5.9, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [6.3, 2.5, 5. , 1.9],
       [5.7, 2.8, 4.5, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6. , 2.2, 5. , 1.5],
       [5.4, 3.9, 1.7, 0.4],
       [6.3, 3.4, 5.6, 2.4],
       [6.2, 3.4, 5.4, 2.3],
       [4.4, 3. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [6.6, 3. , 4.4, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [5.8, 2.7, 5.1, 1.9],
       [5.9, 3.2, 4.8, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [5.8, 2.7, 4.1, 1. ],
       [5.1, 3.5, 1.4, 0.3],
       [7.2, 3. , 5.8, 1.6],
       [5.8, 2.7, 5.1, 1.9],
       [6.7, 3.1, 4.7, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.6, 3.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 2

In [34]:
X_train.shape

(120, 4)

In [36]:
Y_test.shape

(30,)

In [37]:
model=SVC()       # here we create the instance of model or we can say creating the object of the model

In [38]:
model.fit(X_train,Y_train)

SVC()

In [39]:
pred= model.predict(X_test)

In [40]:
pred

array([2, 0, 0, 1, 2, 1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1,
       0, 0, 2, 2, 2, 0, 0, 1])

In [41]:
X_test.shape

(30, 4)

In [42]:
Y_test.shape

(30,)

In [43]:
Y_test

array([2, 0, 0, 1, 1, 1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1,
       0, 0, 1, 2, 2, 0, 0, 1])

In [44]:
model.score(X_test,Y_test)

0.9333333333333333